### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by SHIVApradee** [SHIVApradee/markdown-portfolio#3]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world

**Comment by SHIVApradee** [comment]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
